line.bot:
  channel-token: 'D/K6WfUnu2np+mgbAQVstpKwax2cNFFab6cO3PNDvwnwLfjYjPBhjVsNwhk7T89xsozIl+irEGpDNtc8pYuuChgVpwa6RQS4L82WB/jT/mzES4sOskgEWp8d9RXugAuOED1cLcMZ0phD3zmNVPW7xwdB04t89/1O/w1cDnyilFU='
  channel-secret: 'f2edcb443e1134f81a529d69f60a6d18'
  handler.path: /callback